allowBuilds:
  bufferutil: true
  esbuild: true
  keccak: true
  unrs-resolver: true
  utf-8-validate: true
onlyBuiltDependencies:
  - bufferutil
  - esbuild
  - keccak
  - unrs-resolver
  - utf-8-validate
